version: '2'

services:
  bind:
    restart: always
    image: sameersbn/bind:9.16.1-20200524
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "10000:10000/tcp"
    volumes:
      - "dns-data2:/data"
    environment:
      WEBMIN_INIT_SSL_ENABLED: "false"
      ROOT_PASSWORD: "root"

volumes:
  dns-data2: { }
