version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./logs:/var/log/nginx
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - nginx_net

networks:
  nginx_net:
